import * as Blockly from "blockly";
import { registerSpikeBlocks, toolbox } from "../blocks/catalog";
import { uiText, type Locale } from "../blocks/i18n";
import { BlockRuntime } from "../blocks/runtime";
import { PORTS, type HubTelemetry, type Port, type PortTelemetry, type SpikeHub } from "spike-link";
import { evaluateWatch, watchGroups } from "./watch";
import { formatRgb, tabFromHash, type AppTab } from "./app-tab";

type State = "disconnected" | "connecting" | "connected" | "error";

export class UI {
  private static readonly AUTOSAVE_KEY = "spike-blocks-autosave-v1";
  private static readonly WATCH_KEY = "spike-blocks-watch-v1";
  private locale: Locale = (localStorage.getItem("spike-locale") as Locale) || "en";
  private workspace?: Blockly.WorkspaceSvg;
  private runtime?: BlockRuntime;
  private state: State = "disconnected";
  private logLines: string[] = [];
  private keys = new Set<string>();
  private activeTab: AppTab = tabFromHash(location.hash);
  private selectedPort: Port = "A";
  private consoleOpen = false;
  private hasMotor = false;
  private autosaveTimer?: ReturnType<typeof setTimeout>;
  private watchOpen = false;
  private watchers: Array<{id:number;expression:string}> = this.readWatchers();
  private lastTelemetry?: HubTelemetry;

  constructor(private readonly root: HTMLElement, private readonly hub: SpikeHub) {
    this.render();
    try { const saved=this.readAutosave();this.createWorkspace(saved?.workspace);if(saved?.name)this.el<HTMLInputElement>("project-name").value=saved.name;this.switchTab(this.activeTab); } catch (error) { this.appendLog(error instanceof Error ? `${error.message}\n${error.stack ?? ""}` : String(error), "error"); }
    hub.connection.onDisconnected(() => { this.runtime?.stop();this.updateRun(false);this.hasMotor=false;this.lastTelemetry=undefined;this.state = "disconnected";this.renderWatchPresets();this.updateWatcherValues();this.updateConnection(); });
    hub.onTelemetry(state => this.renderTelemetry(state));
    hub.logger.subscribe(entries => { const latest = entries.at(-1); if (latest) this.appendLog(latest.message, latest.type === "ERROR" ? "error" : "info"); });
    window.addEventListener("keydown", this.keyDown); window.addEventListener("keyup", this.keyUp); window.addEventListener("blur", this.releaseKeys);
    window.addEventListener("beforeunload", () => { this.autosave(); this.releaseHub(); });
    window.addEventListener("pagehide", () => this.releaseHub());
    window.addEventListener("popstate", () => this.switchTab(tabFromHash(location.hash), false));
    if (!location.hash) history.replaceState(null,"",`#/${this.activeTab}`);
  }
  private t(key: Parameters<typeof uiText>[1]): string { return uiText(this.locale, key); }
  private l(en: string, cs: string): string { return this.locale === "cs" ? cs : en; }
  private render(): void {
    document.documentElement.lang = this.locale;
    this.root.innerHTML = `<main class="app-shell"><header class="app-header"><div class="brand"><div class="brand-mark">S</div><div><strong>${this.t("appName")}</strong><span>Prime · Web Bluetooth</span></div></div><input id="project-name" class="project-name" value="${this.t("project")}" aria-label="Project name"><div class="header-actions"><button id="new" class="quiet">${this.t("newProject")}</button><button id="load" class="quiet">${this.t("load")}</button><button id="save" class="quiet">${this.t("save")}</button><input id="file-input" type="file" accept=".spikeblocks,.json" hidden><label class="language"><span>Language</span><select id="locale"><option value="en" ${this.locale === "en" ? "selected" : ""}>EN</option><option value="cs" ${this.locale === "cs" ? "selected" : ""}>CS</option></select></label><button id="connect" class="connect"><i></i><span>${this.t("connect")}</span></button></div></header>
    <nav class="app-tabs"><a id="tab-controller" class="active" href="#/controller">${this.l("Controller","Ovladač")}</a><a id="tab-blocks" href="#/blocks">${this.l("Word Blocks","Bloky")}</a></nav>
    <section id="blocks-view" class="blocks-view hidden offline"><section class="runbar"><div class="connection-copy"><div class="connection-line"><span id="connection-state">${this.t("disconnected")}</span><div class="quick-ports" aria-label="${this.l("Connected devices","Připojená zařízení")}">${PORTS.map(port=>`<div id="quick-port-${port}" class="quick-port empty" title="${this.l("Port is empty","Port je prázdný")}"><b>${port}</b><span>—</span></div>`).join("")}</div></div><small id="run-state">${this.t("keysHint")}</small></div><div id="offline-notice" class="offline-notice"><i></i><div><strong id="offline-title">${this.t("offlineTitle")}</strong><span id="offline-hint">${this.t("offlineHint")}</span></div></div><div class="run-tools"><div class="history-actions"><button id="undo" title="${this.t("undo")} · Ctrl/Cmd+Z" aria-label="${this.t("undo")}" disabled><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 7 4 12l5 5M5 12h8a6 6 0 0 1 6 6"/></svg></button><button id="redo" title="${this.t("redo")} · Ctrl/Cmd+Shift+Z" aria-label="${this.t("redo")}" disabled><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m15 7 5 5-5 5m4-5h-8a6 6 0 0 0-6 6"/></svg></button></div><label class="example-picker"><span>${this.t("examples")}</span><select id="example"><option value="">${this.t("chooseExample")}</option><option value="keyboard-drive">${this.t("keyboardDrive")}</option></select></label><div class="run-actions"><button id="run" class="run-button" aria-label="${this.t("run")}" disabled>▶</button><button id="stop" class="stop-button" aria-label="${this.t("stop")}" disabled>■</button></div></div></section><section class="editor-shell"><div id="blockly" class="blockly-host"></div></section></section>
    <section id="controller-view" class="controller-view"><div class="controller-grid"><article class="control-card connection-card"><div><span class="card-label">${this.l("Connection","Připojení")}</span><h2 id="controller-status">${this.t("disconnected")}</h2></div><p>${this.l("The original BLE controller and live hub diagnostics remain available here.","Původní BLE ovladač a živá diagnostika hubu zůstávají dostupné zde.")}</p></article>
    <article class="control-card motor-card"><div class="card-head"><div><span class="card-label">${this.l("Motor control","Ovládání motoru")}</span><h2>${this.l("Single port","Jeden port")}</h2></div><select id="motor-port">${PORTS.map(p=>`<option>${p}</option>`).join("")}</select></div><div class="motor-buttons"><button id="reverse"><strong>−30</strong>${this.l("Reverse","Zpět")}</button><button id="motor-stop" class="danger"><strong>■</strong>${this.l("Stop","Stop")}</button><button id="forward"><strong>+30</strong>${this.l("Forward","Vpřed")}</button></div></article>
    <article class="control-card telemetry-card"><div class="card-head"><div><span class="card-label">${this.l("Live state","Živý stav")}</span><h2>${this.l("Hub & devices","Hub a zařízení")}</h2></div><span id="telemetry-live" class="live-pill">${this.l("Waiting","Čekám")}</span></div><div class="hub-values rich"><div><span>${this.l("Battery","Baterie")}</span><strong id="battery">—</strong></div><div><span>Yaw</span><strong id="yaw">—</strong></div><div><span>Pitch</span><strong id="pitch">—</strong></div><div><span>Roll</span><strong id="roll">—</strong></div><div><span>${this.l("Face up","Strana nahoře")}</span><strong id="face">—</strong></div><div><span>${this.l("Yaw face","Směr yaw")}</span><strong id="yaw-face">—</strong></div><div class="wide"><span>${this.l("Acceleration X / Y / Z","Zrychlení X / Y / Z")}</span><strong id="acceleration">—</strong></div><div class="wide"><span>${this.l("Gyroscope X / Y / Z","Gyroskop X / Y / Z")}</span><strong id="gyroscope">—</strong></div><div class="matrix-value"><span>5×5 ${this.l("display","displej")}</span><div id="hub-matrix" class="hub-matrix">${"<i></i>".repeat(25)}</div></div></div><div id="port-grid" class="port-grid">${PORTS.map(p=>`<div id="port-${p}" class="port-tile empty"><b>${p}</b><div><strong>${this.l("No device","Bez zařízení")}</strong><span>${this.l("Port is empty","Port je prázdný")}</span></div></div>`).join("")}</div></article></div></section>
    <button id="console-toggle" class="console-toggle" aria-controls="console-panel" aria-expanded="${this.consoleOpen}" aria-label="${this.consoleOpen?this.t("hideConsole"):this.t("showConsole")}"><span>›_</span><b>${this.t("console")}</b></button>
    <aside id="console-panel" class="console-panel ${this.consoleOpen?"open":""}" aria-hidden="${!this.consoleOpen}"><div class="console-head"><strong>${this.t("console")}</strong><div><button id="copy-log" title="${this.t("copyConsole")}">${this.t("copyConsole")}</button><button id="clear-log">${this.t("clearConsole")}</button><button id="close-console" title="${this.t("hideConsole")}" aria-label="${this.t("hideConsole")}">×</button></div></div><pre id="console-log">${this.logLines.length?this.logLines.join("\n"):this.t("ready")}</pre></aside>
    <button id="watch-toggle" class="watch-toggle ${this.watchOpen?"open":""}" aria-controls="watch-panel" aria-expanded="${this.watchOpen}"><span>◎</span><b>${this.t("watch")}</b></button><aside id="watch-panel" class="watch-panel ${this.watchOpen?"open":""}" aria-hidden="${!this.watchOpen}"><div class="watch-head"><strong>${this.t("watch")}</strong><button id="close-watch" aria-label="${this.l("Close watch panel","Zavřít panel Watch")}">×</button></div><form id="watch-form"><select id="watch-preset" aria-label="${this.l("Available live values","Dostupné živé hodnoty")}"></select><input id="watch-expression" placeholder="${this.t("watchExpression")}" autocomplete="off"><button>${this.t("addWatch")}</button></form><div id="watch-list" class="watch-list"></div></aside></main>`;
    this.bind(); this.renderWatchers(); this.updateConnection();
  }
  private bind(): void {
    this.el("connect").addEventListener("click", () => void (this.hub.connected ? this.disconnect() : this.connect()));
    this.el("run").addEventListener("click", () => { this.runtime?.start(); this.updateRun(true); });
    this.el("stop").addEventListener("click", () => { this.runtime?.stop(); this.updateRun(false); });
    this.el<HTMLSelectElement>("example").addEventListener("change", event => this.loadExample((event.target as HTMLSelectElement).value));
    this.el("undo").addEventListener("click", () => this.history(false));
    this.el("redo").addEventListener("click", () => this.history(true));
    this.el("locale").addEventListener("change", e => this.changeLocale((e.target as HTMLSelectElement).value as Locale));
    this.el("save").addEventListener("click", () => this.save()); this.el("load").addEventListener("click", () => this.el<HTMLInputElement>("file-input").click());
    this.el<HTMLInputElement>("file-input").addEventListener("change", e => void this.load((e.target as HTMLInputElement).files?.[0]));
    this.el("new").addEventListener("click", () => { if (confirm(this.locale === "cs" ? "Vymazat současný projekt?" : "Clear the current project?")) this.workspace?.clear(); });
    this.el<HTMLInputElement>("project-name").addEventListener("input", () => this.scheduleAutosave());
    this.el("clear-log").addEventListener("click", () => { this.logLines=[]; this.el("console-log").textContent=this.t("ready"); });
    this.el("copy-log").addEventListener("click", () => void this.copyConsole());
    this.el("console-toggle").addEventListener("click", () => this.setConsoleOpen(!this.consoleOpen));
    this.el("close-console").addEventListener("click", () => this.setConsoleOpen(false));
    this.el("watch-toggle").addEventListener("click", () => this.setWatchOpen(!this.watchOpen));
    this.el("close-watch").addEventListener("click", () => this.setWatchOpen(false));
    this.el<HTMLFormElement>("watch-form").addEventListener("submit", event => {event.preventDefault();this.addWatcher();});
    this.el<HTMLSelectElement>("watch-preset").addEventListener("change", event => {const select=event.target as HTMLSelectElement;if(!select.value)return;this.el<HTMLInputElement>("watch-expression").value=select.value;this.el<HTMLInputElement>("watch-expression").focus();});
    this.el("tab-controller").addEventListener("click", event => { event.preventDefault();this.switchTab("controller"); });
    this.el("tab-blocks").addEventListener("click", event => { event.preventDefault();this.switchTab("blocks"); });
    this.el<HTMLSelectElement>("motor-port").addEventListener("change", e => this.selectedPort=(e.target as HTMLSelectElement).value as Port);
    this.el("forward").addEventListener("click",()=>void this.motor(30)); this.el("reverse").addEventListener("click",()=>void this.motor(-30)); this.el("motor-stop").addEventListener("click",()=>void this.motor(0));
  }
  private createWorkspace(state?: object): void {
    this.runtime?.dispose(); registerSpikeBlocks(this.locale); this.workspace?.dispose();
    this.workspace = Blockly.inject(this.el("blockly"), { toolbox: toolbox(this.locale) as never, renderer: "zelos", theme: Blockly.Themes.Classic, trashcan: true, comments: true, collapse: false, sounds: false, grid: { spacing: 24, length: 2, colour: "#d9dde6", snap: false }, zoom: { controls: true, wheel: true, startScale: .82, maxScale: 1.4, minScale: .45, scaleSpeed: 1.1 }, move: { scrollbars: true, drag: true, wheel: true } });
    if (state) Blockly.serialization.workspaces.load(state, this.workspace);
    this.workspace.addChangeListener(event => { if (!event.isUiEvent) this.scheduleAutosave();queueMicrotask(()=>this.updateHistory()); });
    this.runtime = new BlockRuntime(this.workspace, this.hub, (message, kind) => this.appendLog(message, kind)); this.centerProgram();
    this.updateHistory();
  }
  private changeLocale(locale: Locale): void { const state=this.workspace?Blockly.serialization.workspaces.save(this.workspace):undefined;const name=this.el<HTMLInputElement>("project-name").value;this.locale=locale;localStorage.setItem("spike-locale",locale);this.render();this.el<HTMLInputElement>("project-name").value=name;this.createWorkspace(state);this.switchTab(this.activeTab); }
  private async connect(): Promise<void> { this.state="connecting";this.updateConnection();try{await this.hub.connect();this.state="connected";this.appendLog(this.t("connected"));}catch(error){this.state="error";this.appendLog(error instanceof Error?error.message:String(error),"error");}this.updateConnection(); }
  private disconnect(): void { this.releaseHub(); this.state="disconnected"; this.updateConnection(); }
  private releaseHub(): void { this.runtime?.stop(false); void this.hub.shutdown(); }
  private updateConnection(): void { const button=this.root.querySelector<HTMLButtonElement>("#connect");if(!button)return;button.className=`connect ${this.state}`;button.querySelector("span")!.textContent=this.state==="connected"?this.t("disconnect"):this.state==="connecting"?this.t("connecting"):this.t("connect");button.disabled=this.state==="connecting";const label=this.state==="connected"?this.t("connected"):this.state==="connecting"?this.t("connecting"):this.t("disconnected");this.el("connection-state").textContent=label;this.el("controller-status").textContent=label;const online=this.state==="connected",ready=online&&this.hasMotor;if(!online)this.resetQuickPorts();this.el("offline-title").textContent=online?this.t("noMotorTitle"):this.t("offlineTitle");this.el("offline-hint").textContent=online?this.t("noMotorHint"):this.t("offlineHint");this.el("blocks-view").classList.toggle("offline",!ready);this.el("offline-notice").classList.toggle("hidden",ready);this.el<HTMLButtonElement>("run").disabled=!ready||!!this.runtime?.running;this.el<HTMLButtonElement>("stop").disabled=!ready||!this.runtime?.running; }
  private updateRun(running:boolean):void{this.el("run-state").textContent=running?this.t("running"):this.t("stopped");this.el("run").classList.toggle("active",running);const ready=this.state==="connected"&&this.hasMotor;this.el<HTMLButtonElement>("run").disabled=!ready||running;this.el<HTMLButtonElement>("stop").disabled=!ready||!running;}
  private switchTab(tab:AppTab,updateRoute=true):void{this.activeTab=tab;this.el("controller-view").classList.toggle("hidden",tab!=="controller");this.el("blocks-view").classList.toggle("hidden",tab!=="blocks");this.el("tab-controller").classList.toggle("active",tab==="controller");this.el("tab-blocks").classList.toggle("active",tab==="blocks");for(const id of ["new","load","save"])this.el(id).classList.toggle("hidden",tab!=="blocks");if(updateRoute&&location.hash!==`#/${tab}`)history.pushState(null,"",`#/${tab}`);if(tab==="blocks"&&this.workspace)requestAnimationFrame(()=>Blockly.svgResize(this.workspace!));}
  private async motor(power:number):Promise<void>{try{if(!this.hub.connected)throw new Error(this.l("Connect the hub first.","Nejprve připojte hub."));await this.hub.sendCommand(power===0?{cmd:"motor.stop",port:this.selectedPort}:{cmd:"motor.run",port:this.selectedPort,speed:power});}catch(error){this.appendLog(error instanceof Error?error.message:String(error),"error");}}
  private renderTelemetry(state:HubTelemetry):void{this.lastTelemetry=state;const set=(id:string,value:string)=>{const el=this.root.querySelector(`#${id}`);if(el)el.textContent=value;};set("battery",state.battery===undefined?"—":`${state.battery}%`);set("yaw",state.imu?`${state.imu.yaw.toFixed(1)}°`:"—");set("pitch",state.imu?`${state.imu.pitch.toFixed(1)}°`:"—");set("roll",state.imu?`${state.imu.roll.toFixed(1)}°`:"—");set("face",state.imu?.face??"—");set("yaw-face",state.imu?.yawFace??"—");set("acceleration",state.imu?.acceleration.join(" / ")??"—");set("gyroscope",state.imu?.gyroscope.join(" / ")??"—");set("telemetry-live",this.l("Live · 4 Hz","Živě · 4 Hz"));const pixels=this.root.querySelectorAll("#hub-matrix i");(state.matrix??[]).forEach((value,index)=>{const pixel=pixels[index] as HTMLElement|undefined;if(pixel)pixel.style.opacity=String(Math.max(.08,value/100));});for(const port of PORTS)this.renderPort(port,state.ports[port]);const hadMotor=this.hasMotor;this.hasMotor=PORTS.some(port=>state.ports[port]?.kind==="motor");if(hadMotor&&!this.hasMotor&&this.runtime?.running){this.runtime.stop();this.updateRun(false);}this.renderWatchPresets();this.updateWatcherValues();this.updateConnection();}
  private renderPort(port:Port,device?:PortTelemetry):void{const el=this.root.querySelector(`#port-${port}`);if(!el)return;el.className=`port-tile ${device?.kind??"empty"}`;let title=this.l("No device","Bez zařízení"),value="—",detail=this.l("Port is empty","Port je prázdný"),dot="";if(device?.kind==="motor"){const motorType=device.motorType==="large"?this.l("Large","Velký"):device.motorType==="small"?this.l("Small","Malý"):device.motorType==="medium"?this.l("Medium","Střední"):this.l("Unknown","Neznámý"),running=Math.abs(device.speed)>0||Math.abs(device.power)>.5;title=`${motorType} ${this.l("motor","motor")}`;value=`${device.position}°`;dot=running?"on":"off";detail=`${device.position}° ${this.l("position","pozice")} · ${device.speed}% ${this.l("speed","rychlost")} · ${device.power}% ${this.l("power","výkon")}`;}if(device?.kind==="force"){title=this.l("Button / force","Tlačítko / síla");value=device.pressed?this.l("Pressed","Zmáčknuto"):this.l("Released","Uvolněno");detail=`${device.force}% · ${device.pressed?this.l("pressed","stisknutý"):this.l("released","uvolněný")}`;}if(device?.kind==="color"){title=this.l("Color","Barva");value=this.colorName(device.color);dot=`color-${device.color.toLowerCase()}`;detail=`${this.colorName(device.color)} · ${formatRgb(device.rgb)}`;}if(device?.kind==="distance"){title=this.l("Distance","Vzdálenost");value=device.distance<0?this.l("Out of range","Mimo dosah"):`${(device.distance/10).toFixed(device.distance%10?1:0)} cm`;detail=device.distance<0?this.l("Out of range","Mimo dosah"):`${device.distance} mm`;}if(device?.kind==="color-matrix"){title=this.l("3×3 matrix","Matice 3×3");value=this.l("Connected","Připojena");detail=device.pixels.map(v=>v.toString(16)).join(" ");}el.innerHTML=`<b>${port}</b><div><strong>${title}</strong><span>${detail}</span></div>`;const quick=this.root.querySelector<HTMLElement>(`#quick-port-${port}`);if(quick){quick.className=`quick-port ${device?.kind??"empty"}`;quick.title=`${title} · ${detail}`;quick.innerHTML=`<b>${port}</b><span class="quick-data"><em>${title}</em><span>${dot?`<i class="status-dot ${dot}"></i>`:""}<strong>${value}</strong></span></span>`;}}
  private colorName(color:string):string{if(this.locale==="en")return color;return ({Black:"Černá",Magenta:"Purpurová",Purple:"Fialová",Blue:"Modrá",Azure:"Azurová",Turquoise:"Tyrkysová",Green:"Zelená",Yellow:"Žlutá",Orange:"Oranžová",Red:"Červená",White:"Bílá",Unknown:"Neznámá"} as Record<string,string>)[color]??color;}
  private resetQuickPorts():void{for(const port of PORTS){const quick=this.root.querySelector<HTMLElement>(`#quick-port-${port}`);if(!quick)continue;quick.className="quick-port empty";quick.title=this.l("Port is empty","Port je prázdný");quick.innerHTML=`<b>${port}</b><span class="quick-data"><em>${this.l("Empty","Volný")}</em><span><strong>—</strong></span></span>`;}}
  private history(redo:boolean):void{if(!this.workspace)return;this.workspace.undo(redo);queueMicrotask(()=>this.updateHistory());}
  private updateHistory():void{if(!this.workspace)return;const undo=this.root.querySelector<HTMLButtonElement>("#undo"),redo=this.root.querySelector<HTMLButtonElement>("#redo");if(undo)undo.disabled=this.workspace.getUndoStack().length===0;if(redo)redo.disabled=this.workspace.getRedoStack().length===0;}
  private save(): void { if(!this.workspace)return;const payload={format:"spike-blocks",version:1,locale:this.locale,name:this.el<HTMLInputElement>("project-name").value,workspace:Blockly.serialization.workspaces.save(this.workspace)};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${payload.name.replace(/[^a-z0-9_-]+/gi,"-")||"project"}.spikeblocks`;a.click();URL.revokeObjectURL(url); }
  private async load(file?:File):Promise<void>{if(!file)return;try{const payload=JSON.parse(await file.text()) as {name?:string;locale?:Locale;workspace?:object};if(payload.locale)this.locale=payload.locale;this.render();this.el<HTMLInputElement>("project-name").value=payload.name??this.t("project");this.createWorkspace(payload.workspace??payload);this.appendLog(`Opened ${file.name}`);}catch(error){this.appendLog(error instanceof Error?error.message:String(error),"error");}}
  private keyDown=(event:KeyboardEvent):void=>{if(event.repeat||this.isTyping(event.target))return;if((event.ctrlKey||event.metaKey)&&event.code==="KeyZ"){event.preventDefault();this.history(event.shiftKey);return;}if(event.ctrlKey&&event.code==="KeyY"){event.preventDefault();this.history(true);return;}this.keys.add(event.code);this.runtime?.handleKey(event.code,"pressed");if(this.runtime?.running&&this.isControlKey(event.code))event.preventDefault();};
  private keyUp=(event:KeyboardEvent):void=>{const wasControlled=this.keys.delete(event.code);if(wasControlled)this.runtime?.handleKey(event.code,"released");if(wasControlled&&this.runtime?.running&&this.isControlKey(event.code))event.preventDefault();};
  private releaseKeys=():void=>{for(const code of this.keys)this.runtime?.handleKey(code,"released");this.keys.clear();};
  private setConsoleOpen(open:boolean):void{this.consoleOpen=open;const panel=this.el("console-panel");const toggle=this.el<HTMLButtonElement>("console-toggle");panel.classList.toggle("open",open);panel.setAttribute("aria-hidden",String(!open));toggle.setAttribute("aria-expanded",String(open));toggle.setAttribute("aria-label",open?this.t("hideConsole"):this.t("showConsole"));toggle.classList.toggle("open",open);}
  private setWatchOpen(open:boolean):void{this.watchOpen=open;const panel=this.el("watch-panel");const toggle=this.el<HTMLButtonElement>("watch-toggle");panel.classList.toggle("open",open);panel.setAttribute("aria-hidden",String(!open));toggle.setAttribute("aria-expanded",String(open));toggle.classList.toggle("open",open);if(open)requestAnimationFrame(()=>this.el<HTMLInputElement>("watch-expression").focus());}
  private renderWatchPresets():void{const select=this.root.querySelector<HTMLSelectElement>("#watch-preset");if(!select)return;const groups=watchGroups(this.lastTelemetry,this.locale),signature=JSON.stringify({connected:!!this.lastTelemetry,groups});if(select.dataset.signature===signature)return;const current=select.value;select.replaceChildren();const placeholder=document.createElement("option");placeholder.value="";placeholder.textContent=this.lastTelemetry?this.l("Choose a live value…","Vyberte živou hodnotu…"):this.l("Connect the hub to see values","Připojte hub pro nabídku hodnot");select.append(placeholder);for(const group of groups){const element=document.createElement("optgroup");element.label=group.label;for(const expression of group.expressions){const option=document.createElement("option");option.value=expression;option.textContent=expression;element.append(option);}select.append(element);}select.value=[...select.options].some(option=>option.value===current)?current:"";select.disabled=!this.lastTelemetry;select.dataset.signature=signature;}
  private addWatcher():void{const input=this.el<HTMLInputElement>("watch-expression"),expression=input.value.trim();if(!expression)return;if(!this.watchers.some(item=>item.expression.toLowerCase()===expression.toLowerCase()))this.watchers.push({id:Date.now(),expression});input.value="";this.saveWatchers();this.renderWatchers();}
  private removeWatcher(id:number):void{this.watchers=this.watchers.filter(item=>item.id!==id);this.saveWatchers();this.renderWatchers();}
  private renderWatchers():void{this.renderWatchPresets();const list=this.el("watch-list");list.replaceChildren();if(this.watchers.length===0){const empty=document.createElement("p");empty.className="watch-empty";empty.textContent=this.t("noWatches");list.append(empty);return;}for(const watcher of this.watchers){const row=document.createElement("article");row.className="watch-row";const copy=document.createElement("div"),expression=document.createElement("code"),value=document.createElement("strong"),remove=document.createElement("button");expression.textContent=watcher.expression;value.dataset.watchValue=String(watcher.id);value.textContent="—";copy.append(expression,value);remove.type="button";remove.textContent="×";remove.title=this.l("Remove watcher","Odebrat watcher");remove.setAttribute("aria-label",remove.title);remove.addEventListener("click",()=>this.removeWatcher(watcher.id));row.append(copy,remove);list.append(row);}this.updateWatcherValues();}
  private updateWatcherValues():void{for(const watcher of this.watchers){const value=this.root.querySelector<HTMLElement>(`[data-watch-value="${watcher.id}"]`);if(!value)continue;const result=evaluateWatch(watcher.expression,this.lastTelemetry,this.locale);value.textContent=result.value;value.className=result.valid?(result.tone??""):"invalid";}}
  private saveWatchers():void{localStorage.setItem(UI.WATCH_KEY,JSON.stringify(this.watchers));}
  private readWatchers():Array<{id:number;expression:string}>{try{const value=JSON.parse(localStorage.getItem(UI.WATCH_KEY)??"[]") as unknown;if(!Array.isArray(value))return [];return value.filter((item):item is {id:number;expression:string}=>!!item&&typeof item==="object"&&typeof (item as {id?:unknown}).id==="number"&&typeof (item as {expression?:unknown}).expression==="string").slice(0,30);}catch{return [];}}
  private async copyConsole():Promise<void>{const text=this.el("console-log").textContent??"";const button=this.el<HTMLButtonElement>("copy-log");try{await navigator.clipboard.writeText(text);button.textContent=this.t("copied");setTimeout(()=>{if(button.isConnected)button.textContent=this.t("copyConsole");},1400);}catch{this.appendLog(this.l("Could not copy the console.","Obsah konzole se nepodařilo zkopírovat."),"error");}}
  private loadExample(id:string):void{const picker=this.el<HTMLSelectElement>("example");if(!id||!this.workspace)return;const hasBlocks=this.workspace.getAllBlocks(false).length>0;if(hasBlocks&&!confirm(this.l("Replace the current program with this example?","Nahradit současný program touto ukázkou?"))){picker.value="";return;}this.runtime?.stop();this.workspace.clear();if(id==="keyboard-drive")this.createKeyboardDriveExample();this.el<HTMLInputElement>("project-name").value=this.t("keyboardDrive");picker.value="";this.autosave();}
  private createKeyboardDriveExample():void{if(!this.workspace)return;const workspace=this.workspace;const stack=(key:string,state:"pressed"|"released",action:"forward"|"backward"|"left"|"right"|"stop",x:number,y:number)=>{const event=workspace.newBlock("spike_event_key") as Blockly.BlockSvg;event.setFieldValue(key,"KEY");event.setFieldValue(state,"STATE");let command:Blockly.BlockSvg;if(action==="stop")command=workspace.newBlock("spike_move_stop") as Blockly.BlockSvg;else if(action==="forward"||action==="backward"){command=workspace.newBlock("spike_move_start") as Blockly.BlockSvg;command.setFieldValue(action,"DIR");}else{command=workspace.newBlock("spike_move_steer_start") as Blockly.BlockSvg;const number=workspace.newBlock("math_number") as Blockly.BlockSvg;number.setFieldValue(action==="left"?-100:100,"NUM");number.initSvg();command.getInput("STEERING")!.connection!.connect(number.outputConnection!);}event.nextConnection!.connect(command.previousConnection!);event.initSvg();command.initSvg();event.render();command.render();event.moveBy(x,y);};Blockly.Events.setGroup(true);try{stack("ArrowUp","pressed","forward",40,40);stack("ArrowUp","released","stop",400,40);stack("ArrowDown","pressed","backward",40,180);stack("ArrowDown","released","stop",400,180);stack("ArrowLeft","pressed","left",40,320);stack("ArrowLeft","released","stop",400,320);stack("ArrowRight","pressed","right",40,460);stack("ArrowRight","released","stop",400,460);}finally{Blockly.Events.setGroup(false);}this.centerProgram();}
  private centerProgram():void{requestAnimationFrame(()=>{if(!this.workspace)return;Blockly.svgResize(this.workspace);if(this.workspace.getAllBlocks(false).length>0){this.workspace.zoomToFit();for(let step=0;step<5;step++)this.workspace.zoomCenter(-1);}else this.workspace.scrollCenter();});}
  private isTyping(target:EventTarget|null):boolean{return target instanceof HTMLInputElement||target instanceof HTMLTextAreaElement||target instanceof HTMLSelectElement;}
  private isControlKey(code:string):boolean{return code.startsWith("Arrow")||["Space","Enter","Escape"].includes(code)||/^Key[A-Z]$/.test(code)||/^Digit\d$/.test(code);}
  private appendLog(message:string,kind:"info"|"error"="info"):void{const line=`${new Date().toLocaleTimeString()}  ${kind==="error"?"ERROR":"INFO "}  ${message}`;this.logLines.push(line);this.logLines=this.logLines.slice(-80);const el=this.root.querySelector<HTMLElement>("#console-log");if(el){el.textContent=this.logLines.join("\n");el.scrollTop=el.scrollHeight;}}
  private scheduleAutosave():void{if(this.autosaveTimer)clearTimeout(this.autosaveTimer);this.autosaveTimer=setTimeout(()=>this.autosave(),250);}
  private autosave():void{if(!this.workspace)return;if(this.autosaveTimer)clearTimeout(this.autosaveTimer);this.autosaveTimer=undefined;const payload={version:1,locale:this.locale,name:this.el<HTMLInputElement>("project-name").value,workspace:Blockly.serialization.workspaces.save(this.workspace)};localStorage.setItem(UI.AUTOSAVE_KEY,JSON.stringify(payload));}
  private readAutosave():{name?:string;workspace?:object}|undefined{try{const raw=localStorage.getItem(UI.AUTOSAVE_KEY);if(!raw)return undefined;const saved=JSON.parse(raw) as {version?:number;name?:string;workspace?:object};return saved.version===1?saved:undefined;}catch{return undefined;}}
  private el<T extends HTMLElement=HTMLElement>(id:string):T{return this.root.querySelector<T>(`#${id}`)!;}
}
