import * as Blockly from "blockly";
import { blockText, uiText, type Locale } from "./i18n";

const C = { motors: "#0794e3", movement: "#f044b8", light: "#8b5de8", sound: "#b35bdc", events: "#f5c400", control: "#ffad1f", sensors: "#35c0dd", operators: "#08b84e", keyboard: "#5968e8" };
const icon = (symbol: string) => ({ type: "field_label", text: symbol });
const drop = (name: string, options: Array<[string, string]>) => ({ type: "field_dropdown", name, options });
const value = (name: string, check?: string) => ({ type: "input_value", name, ...(check ? { check } : {}) });
const field = (name: string, text: string) => ({ type: "field_input", name, text });
const number = (name: string, n: number, min?: number, max?: number) => ({ type: "field_number", name, value: n, ...(min === undefined ? {} : { min }), ...(max === undefined ? {} : { max }) });
const PORTS = ["A", "B", "C", "D", "E", "F"].map(x => [x, x] as [string, string]);
const DIRECTIONS = [["↻", "cw"], ["↺", "ccw"]] as Array<[string, string]>;
const COLORS = [["red", "red"], ["yellow", "yellow"], ["green", "green"], ["blue", "blue"], ["magenta", "magenta"], ["black", "black"], ["white", "white"], ["none", "none"]] as Array<[string, string]>;
const KEYS: Array<[string, string]> = [
  ["↑", "ArrowUp"], ["↓", "ArrowDown"], ["←", "ArrowLeft"], ["→", "ArrowRight"],
  ["Space", "Space"], ["Enter", "Enter"], ["Escape", "Escape"],
  ..."ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("").map(letter => [letter, `Key${letter}`] as [string, string]),
  ..."0123456789".split("").map(digit => [digit, `Digit${digit}`] as [string, string]),
];
const tf = (locale: Locale, en: string, cs: string, value: string): [string, string] => [locale === "cs" ? cs : en, value];

type BlockDef = Record<string, unknown> & { type: string };
const command = (locale: Locale, type: string, key: string, colour: string, args0: unknown[] = [], end = false): BlockDef => ({ type, message0: blockText(locale, key), args0, previousStatement: null, ...(end ? {} : { nextStatement: null }), colour, inputsInline: true });
const reporter = (locale: Locale, type: string, key: string, colour: string, args0: unknown[] = [], output: "Number" | "String" | "Boolean" | null = null): BlockDef => ({ type, message0: blockText(locale, key), args0, output, colour, inputsInline: true, outputShape: output === "Boolean" ? 1 : 2 });
const hat = (locale: Locale, type: string, key: string, colour: string, args0: unknown[] = []): BlockDef => ({ type, message0: blockText(locale, key), args0, nextStatement: null, colour, inputsInline: true, hat: "cap" });
const cblock = (locale: Locale, type: string, key: string, colour: string, args0: unknown[] = [], second = false): BlockDef => ({ type, message0: blockText(locale, key), args0, message1: "%1", args1: [{ type: "input_statement", name: "DO" }], ...(second ? { message2: blockText(locale, "else"), message3: "%1", args3: [{ type: "input_statement", name: "ELSE" }] } : {}), previousStatement: null, nextStatement: null, colour, inputsInline: true });

export function registerSpikeBlocks(locale: Locale): void {
  Blockly.Blocks.math_number = { init() { this.jsonInit({ type: "math_number", message0: "%1", args0: [{ type: "field_number", name: "NUM", value: 0 }], output: "Number", outputShape: 2, colour: "#ffffff" }); } };
  Blockly.Blocks.text = { init() { this.jsonInit({ type: "text", message0: "%1", args0: [{ type: "field_input", name: "TEXT", text: "" }], output: "String", outputShape: 2, colour: "#ffffff" }); } };
  const brake = [tf(locale, "brake", "brzdit", "brake"), tf(locale, "hold", "držet", "hold"), tf(locale, "coast", "volně", "coast")];
  const accel = [tf(locale, "slow", "pomalé", "slow"), tf(locale, "medium", "střední", "medium"), tf(locale, "fast", "rychlé", "fast")];
  const distanceUnits = [["%", "%"], ["cm", "cm"], ["in", "in"]] as Array<[string, string]>;
  const blocks: BlockDef[] = [
    command(locale,"spike_motor_run_for","runFor",C.motors,[icon("⚙"),drop("PORT",PORTS),drop("DIR",DIRECTIONS),value("AMOUNT","Number"),drop("UNIT",[["rotations","rotations"],["degrees","degrees"],["seconds","seconds"]])]),
    command(locale,"spike_motor_run_to","runTo",C.motors,[icon("⚙"),drop("PORT",PORTS),value("POSITION","Number"),value("SPEED","Number")]),
    command(locale,"spike_motor_start","startMotor",C.motors,[icon("⚙"),drop("PORT",PORTS),drop("DIR",DIRECTIONS)]), command(locale,"spike_motor_stop","stopMotor",C.motors,[icon("⚙"),drop("PORT",PORTS)]),
    reporter(locale,"spike_motor_position","motorPosition",C.motors,[icon("⚙"),drop("PORT",PORTS)],"Number"), reporter(locale,"spike_motor_speed","motorSpeed",C.motors,[icon("⚙"),drop("PORT",PORTS)],"Number"),
    command(locale,"spike_motor_set_relative","setRelative",C.motors,[icon("⚙"),drop("PORT",PORTS),value("POSITION","Number")]), reporter(locale,"spike_motor_relative","relativePosition",C.motors,[icon("⚙"),drop("PORT",PORTS)],"Number"),
    command(locale,"spike_motor_power_start","startPower",C.motors,[icon("⚙"),drop("PORT",PORTS),value("POWER","Number")]), reporter(locale,"spike_motor_power","motorPower",C.motors,[icon("⚙"),drop("PORT",PORTS)],"Number"),
    command(locale,"spike_motor_stop_mode","setStop",C.motors,[icon("⚙"),drop("PORT",PORTS),drop("MODE",brake)]), command(locale,"spike_motor_acceleration","setAcceleration",C.motors,[icon("⚙"),drop("PORT",PORTS),drop("ACCEL",accel)]),
    command(locale,"spike_move_for","moveFor",C.movement,[icon("◉"),drop("DIR",[["↑","forward"],["↓","backward"]]),value("AMOUNT","Number"),drop("UNIT",[["rotations","rotations"],["degrees","degrees"],["seconds","seconds"],["cm","cm"],["in","in"]])]),
    command(locale,"spike_move_start","startMoving",C.movement,[icon("◉"),drop("DIR",[["↑","forward"],["↓","backward"]])]), command(locale,"spike_move_steer_for","moveSteerFor",C.movement,[icon("◉"),value("STEERING","Number"),value("AMOUNT","Number"),drop("UNIT",[["rotations","rotations"],["degrees","degrees"],["seconds","seconds"]])]),
    command(locale,"spike_move_steer_start","startSteer",C.movement,[icon("◉"),value("STEERING","Number")]), command(locale,"spike_move_stop","stopMoving",C.movement,[icon("◉")]), command(locale,"spike_move_speed","setMoveSpeed",C.movement,[icon("◉"),value("SPEED","Number")]),
    command(locale,"spike_move_motors","setMoveMotors",C.movement,[icon("◉"),drop("PAIR",PORTS.flatMap((a,i)=>PORTS.slice(i+1).map(b=>[`${a[0]}+${b[0]}`,`${a[0]}+${b[0]}`] as [string,string])))]), command(locale,"spike_move_wheel","wheelSize",C.movement,[icon("◉"),value("DISTANCE","Number"),drop("UNIT",[["cm","cm"],["in","in"]])]),
    command(locale,"spike_move_tank","tank",C.movement,[icon("◉"),value("LEFT","Number"),value("RIGHT","Number")]), command(locale,"spike_move_stop_mode","setMoveStop",C.movement,[icon("◉"),drop("MODE",brake)]), command(locale,"spike_move_acceleration","setMoveAcceleration",C.movement,[icon("◉"),drop("ACCEL",accel)]),
    command(locale,"spike_light_matrix_for","matrixFor",C.light,[icon("▦"),field("IMAGE","♥"),value("SECONDS","Number")]), command(locale,"spike_light_matrix","matrixOn",C.light,[icon("▦"),field("IMAGE","♥")]), command(locale,"spike_light_write","write",C.light,[icon("▦"),value("TEXT")]), command(locale,"spike_light_off","pixelsOff",C.light,[icon("▦")]),
    command(locale,"spike_light_brightness","brightness",C.light,[icon("▦"),value("BRIGHTNESS","Number")]), command(locale,"spike_light_pixel","pixel",C.light,[icon("▦"),value("X","Number"),value("Y","Number"),value("BRIGHTNESS","Number")]), command(locale,"spike_light_rotate","rotate",C.light,[icon("▦"),drop("DIR",DIRECTIONS)]),
    command(locale,"spike_light_orientation","orientation",C.light,[icon("▦"),drop("ORIENTATION",[["upright","upright"],["left","left"],["right","right"],["upside down","down"]])]), command(locale,"spike_light_centre","centreLight",C.light,[icon("▦"),drop("COLOR",COLORS)]), command(locale,"spike_light_distance","distanceLights",C.light,[icon("◉◉"),drop("PORT",PORTS),field("PATTERN","● ●")]),
    command(locale,"spike_sound_play","playSound",C.sound,[drop("SOUND",[["Cat Meow 1","cat_meow_1"],["Applause","applause"],["Boing","boing"],["Cheering","cheering"],["Laser 1","laser_1"]])]), command(locale,"spike_sound_start","startSound",C.sound,[drop("SOUND",[["Cat Meow 1","cat_meow_1"],["Applause","applause"],["Boing","boing"]])]),
    command(locale,"spike_sound_beep_for","beepFor",C.sound,[icon("▦"),value("NOTE","Number"),value("SECONDS","Number")]), command(locale,"spike_sound_beep","startBeep",C.sound,[icon("▦"),value("NOTE","Number")]), command(locale,"spike_sound_stop","stopSounds",C.sound),
    command(locale,"spike_sound_change_effect","changeEffect",C.sound,[drop("EFFECT",[["pitch","pitch"],["pan","pan"]]),value("VALUE","Number")]), command(locale,"spike_sound_set_effect","setEffect",C.sound,[drop("EFFECT",[["pitch","pitch"],["pan","pan"]]),value("VALUE","Number")]), command(locale,"spike_sound_clear_effects","clearEffects",C.sound), command(locale,"spike_sound_change_volume","changeVolume",C.sound,[value("VALUE","Number")]), command(locale,"spike_sound_set_volume","setVolume",C.sound,[value("VALUE","Number")]), reporter(locale,"spike_sound_volume","volume",C.sound,[],"Number"),
    hat(locale,"spike_event_start","programStarts",C.events), hat(locale,"spike_event_colour","colourEvent",C.events,[icon("◉"),drop("PORT",PORTS),drop("COLOR",COLORS)]), hat(locale,"spike_event_force","forceEvent",C.events,[icon("↔"),drop("PORT",PORTS),drop("STATE",[["pressed","pressed"],["released","released"]])]),
    hat(locale,"spike_event_distance","distanceEvent",C.events,[icon("◉◉"),drop("PORT",PORTS),drop("COMPARE",[["closer than","lt"],["farther than","gt"]]),value("DISTANCE","Number"),drop("UNIT",distanceUnits)]), hat(locale,"spike_event_tilted","tiltedEvent",C.events,[icon("▦"),drop("DIR",[["↑","up"],["↓","down"],["←","left"],["→","right"]])]),
    hat(locale,"spike_event_face","faceEvent",C.events,[icon("▦"),drop("FACE",[["front","front"],["back","back"],["top","top"],["bottom","bottom"],["left","left"],["right","right"]])]), hat(locale,"spike_event_gesture","gestureEvent",C.events,[icon("▦"),drop("GESTURE",[["shaken","shaken"],["tapped","tapped"],["falling","falling"]])]),
    hat(locale,"spike_event_button","buttonEvent",C.events,[icon("▦"),drop("BUTTON",[["Left","left"],["Right","right"]]),drop("STATE",[["pressed","pressed"],["released","released"]])]), hat(locale,"spike_event_timer","timerEvent",C.events,[value("SECONDS","Number")]), hat(locale,"spike_event_condition","conditionEvent",C.events,[value("CONDITION","Boolean")]),
    hat(locale,"spike_event_receive","receive",C.events,[field("MESSAGE","message1")]), command(locale,"spike_event_broadcast","broadcast",C.events,[field("MESSAGE","message1")]), command(locale,"spike_event_broadcast_wait","broadcastWait",C.events,[field("MESSAGE","message1")]),
    hat(locale,"spike_event_key","keyEvent",C.events,[drop("KEY",KEYS),drop("STATE",[tf(locale,"pressed","stisknutá","pressed"),tf(locale,"released","uvolněná","released")])]),
    command(locale,"spike_control_wait","wait",C.control,[value("SECONDS","Number")]), cblock(locale,"spike_control_repeat","repeat",C.control,[value("TIMES","Number")]), cblock(locale,"spike_control_forever","forever",C.control), cblock(locale,"spike_control_if","if",C.control,[value("CONDITION","Boolean")]), cblock(locale,"spike_control_if_else","ifElse",C.control,[value("CONDITION","Boolean")],true), command(locale,"spike_control_wait_until","waitUntil",C.control,[value("CONDITION","Boolean")]), cblock(locale,"spike_control_repeat_until","repeatUntil",C.control,[value("CONDITION","Boolean")]), command(locale,"spike_control_stop_other","stopOther",C.control), command(locale,"spike_control_stop","stop",C.control,[drop("WHAT",[["all","all"],["this stack","stack"]])],true),
    reporter(locale,"spike_sensor_colour_is","colourIs",C.sensors,[icon("◉"),drop("PORT",PORTS),drop("COLOR",COLORS)],"Boolean"), reporter(locale,"spike_sensor_colour","colour",C.sensors,[icon("◉"),drop("PORT",PORTS)],"String"), reporter(locale,"spike_sensor_reflection_compare","reflection",C.sensors,[icon("◉"),drop("PORT",PORTS),drop("COMPARE",[["<","lt"],[">","gt"],["=","eq"]]),value("VALUE","Number")],"Boolean"), reporter(locale,"spike_sensor_reflection","reflected",C.sensors,[icon("◉"),drop("PORT",PORTS)],"Number"),
    reporter(locale,"spike_sensor_force_is","pressed",C.sensors,[icon("↔"),drop("PORT",PORTS),drop("STATE",[["pressed","pressed"],["released","released"]])],"Boolean"), reporter(locale,"spike_sensor_pressure","pressure",C.sensors,[icon("↔"),drop("PORT",PORTS),drop("UNIT",[["%","%"],["N","N"]])],"Number"), reporter(locale,"spike_sensor_distance_compare","closer",C.sensors,[icon("◉◉"),drop("PORT",PORTS),drop("COMPARE",[["closer than","lt"],["farther than","gt"]]),value("VALUE","Number"),drop("UNIT",distanceUnits)],"Boolean"), reporter(locale,"spike_sensor_distance","distance",C.sensors,[icon("◉◉"),drop("PORT",PORTS),drop("UNIT",distanceUnits)],"Number"),
    reporter(locale,"spike_sensor_tilted","isTilted",C.sensors,[icon("▦"),drop("DIR",[["↑","up"],["↓","down"],["←","left"],["→","right"]])],"Boolean"), reporter(locale,"spike_sensor_face","isFace",C.sensors,[icon("▦"),drop("FACE",[["front","front"],["back","back"],["top","top"],["bottom","bottom"],["left","left"],["right","right"]])],"Boolean"), reporter(locale,"spike_sensor_gesture","isGesture",C.sensors,[icon("▦"),drop("GESTURE",[["shaken","shaken"],["tapped","tapped"],["falling","falling"]])],"Boolean"), reporter(locale,"spike_sensor_angle","angle",C.sensors,[icon("▦"),drop("ANGLE",[["yaw","yaw"],["pitch","pitch"],["roll","roll"]])],"Number"), command(locale,"spike_sensor_yaw_zero","yawZero",C.sensors,[icon("▦")]), reporter(locale,"spike_sensor_timer","timer",C.sensors,[],"Number"), command(locale,"spike_sensor_timer_reset","resetTimer",C.sensors), reporter(locale,"spike_sensor_button","isButton",C.sensors,[icon("▦"),drop("BUTTON",[["Left","left"],["Right","right"]]),drop("STATE",[["pressed","pressed"],["released","released"]])],"Boolean"),
    reporter(locale,"spike_operator_random","random",C.operators,[value("FROM","Number"),value("TO","Number")],"Number"), ...([["add","add"],["subtract","subtract"],["multiply","multiply"],["divide","divide"]] as const).map(([type,key])=>reporter(locale,`spike_operator_${type}`,key,C.operators,[value("A","Number"),value("B","Number")],"Number")),
    ...([["lt","lt"],["eq","eq"],["gt","gt"]] as const).map(([type,key])=>reporter(locale,`spike_operator_${type}`,key,C.operators,[value("A"),value("B")],"Boolean")), reporter(locale,"spike_operator_and","and",C.operators,[value("A","Boolean"),value("B","Boolean")],"Boolean"), reporter(locale,"spike_operator_or","or",C.operators,[value("A","Boolean"),value("B","Boolean")],"Boolean"), reporter(locale,"spike_operator_not","not",C.operators,[value("A","Boolean")],"Boolean"),
    reporter(locale,"spike_operator_between","between",C.operators,[value("VALUE","Number"),value("MIN","Number"),value("MAX","Number")],"Boolean"), reporter(locale,"spike_operator_join","join",C.operators,[value("A"),value("B")],"String"), reporter(locale,"spike_operator_letter","letter",C.operators,[value("INDEX","Number"),value("TEXT")],"String"), reporter(locale,"spike_operator_length","length",C.operators,[value("TEXT")],"Number"), reporter(locale,"spike_operator_contains","contains",C.operators,[value("TEXT"),value("PART")],"Boolean"), reporter(locale,"spike_operator_mod","mod",C.operators,[value("A","Number"),value("B","Number")],"Number"), reporter(locale,"spike_operator_round","round",C.operators,[value("VALUE","Number")],"Number"), reporter(locale,"spike_operator_mathop","mathop",C.operators,[drop("OP",[["abs","abs"],["floor","floor"],["ceiling","ceil"],["sqrt","sqrt"],["sin","sin"],["cos","cos"],["tan","tan"],["ln","ln"],["log","log"],["e ^","exp"],["10 ^","pow10"]]),value("VALUE","Number")],"Number"),
  ];
  for (const def of blocks) Blockly.Blocks[def.type] = { init() { this.jsonInit(def); } };
}

const numShadow = (n: number) => ({ shadow: { type: "math_number", fields: { NUM: n } } });
const textShadow = (s: string) => ({ shadow: { type: "text", fields: { TEXT: s } } });
const b = (type: string, inputs: Record<string, unknown> = {}) => ({ kind: "block", type, inputs });
const category = (name: string, colour: string, contents: unknown[]) => ({ kind: "category", name, colour, contents });

export function toolbox(locale: Locale): Record<string, unknown> {
  const t = (key: Parameters<typeof uiText>[1]) => uiText(locale,key);
  return { kind: "categoryToolbox", contents: [
    category(t("motors"),C.motors,[b("spike_motor_run_for",{AMOUNT:numShadow(1)}),b("spike_motor_run_to",{POSITION:numShadow(0),SPEED:numShadow(100)}),b("spike_motor_start"),b("spike_motor_stop"),b("spike_motor_position"),b("spike_motor_speed"),b("spike_motor_set_relative",{POSITION:numShadow(0)}),b("spike_motor_relative"),b("spike_motor_power_start",{POWER:numShadow(100)}),b("spike_motor_power"),b("spike_motor_stop_mode"),b("spike_motor_acceleration")]),
    category(t("movement"),C.movement,[b("spike_move_for",{AMOUNT:numShadow(10)}),b("spike_move_start"),b("spike_move_steer_for",{STEERING:numShadow(30),AMOUNT:numShadow(10)}),b("spike_move_steer_start",{STEERING:numShadow(30)}),b("spike_move_stop"),b("spike_move_speed",{SPEED:numShadow(50)}),b("spike_move_motors"),b("spike_move_wheel",{DISTANCE:numShadow(17.5)}),b("spike_move_tank",{LEFT:numShadow(50),RIGHT:numShadow(50)}),b("spike_move_stop_mode"),b("spike_move_acceleration")]),
    category(t("light"),C.light,[b("spike_light_matrix_for",{SECONDS:numShadow(2)}),b("spike_light_matrix"),b("spike_light_write",{TEXT:textShadow("Hello")}),b("spike_light_off"),b("spike_light_brightness",{BRIGHTNESS:numShadow(75)}),b("spike_light_pixel",{X:numShadow(1),Y:numShadow(1),BRIGHTNESS:numShadow(100)}),b("spike_light_rotate"),b("spike_light_orientation"),b("spike_light_centre"),b("spike_light_distance")]),
    category(t("sound"),C.sound,[b("spike_sound_play"),b("spike_sound_start"),b("spike_sound_beep_for",{NOTE:numShadow(60),SECONDS:numShadow(.2)}),b("spike_sound_beep",{NOTE:numShadow(60)}),b("spike_sound_stop"),b("spike_sound_change_effect",{VALUE:numShadow(10)}),b("spike_sound_set_effect",{VALUE:numShadow(100)}),b("spike_sound_clear_effects"),b("spike_sound_change_volume",{VALUE:numShadow(-10)}),b("spike_sound_set_volume",{VALUE:numShadow(100)}),b("spike_sound_volume")]),
    category(t("events"),C.events,[b("spike_event_start"),b("spike_event_key"),b("spike_event_colour"),b("spike_event_force"),b("spike_event_distance",{DISTANCE:numShadow(8)}),b("spike_event_tilted"),b("spike_event_face"),b("spike_event_gesture"),b("spike_event_button"),b("spike_event_timer",{SECONDS:numShadow(10)}),b("spike_event_condition"),b("spike_event_receive"),b("spike_event_broadcast"),b("spike_event_broadcast_wait")]),
    category(t("control"),C.control,[b("spike_control_wait",{SECONDS:numShadow(1)}),b("spike_control_repeat",{TIMES:numShadow(10)}),b("spike_control_forever"),b("spike_control_if"),b("spike_control_if_else"),b("spike_control_wait_until"),b("spike_control_repeat_until"),b("spike_control_stop_other"),b("spike_control_stop")]),
    category(t("sensors"),C.sensors,[b("spike_sensor_colour_is"),b("spike_sensor_colour"),b("spike_sensor_reflection_compare",{VALUE:numShadow(50)}),b("spike_sensor_reflection"),b("spike_sensor_force_is"),b("spike_sensor_pressure"),b("spike_sensor_distance_compare",{VALUE:numShadow(15)}),b("spike_sensor_distance"),b("spike_sensor_tilted"),b("spike_sensor_face"),b("spike_sensor_gesture"),b("spike_sensor_angle"),b("spike_sensor_yaw_zero"),b("spike_sensor_timer"),b("spike_sensor_timer_reset"),b("spike_sensor_button")]),
    category(t("operators"),C.operators,[b("spike_operator_random",{FROM:numShadow(1),TO:numShadow(10)}),b("spike_operator_add",{A:numShadow(0),B:numShadow(0)}),b("spike_operator_subtract",{A:numShadow(0),B:numShadow(0)}),b("spike_operator_multiply",{A:numShadow(0),B:numShadow(0)}),b("spike_operator_divide",{A:numShadow(0),B:numShadow(0)}),b("spike_operator_lt",{A:numShadow(0),B:numShadow(100)}),b("spike_operator_eq",{A:numShadow(0),B:numShadow(100)}),b("spike_operator_gt",{A:numShadow(0),B:numShadow(100)}),b("spike_operator_and"),b("spike_operator_or"),b("spike_operator_not"),b("spike_operator_between",{VALUE:numShadow(0),MIN:numShadow(-10),MAX:numShadow(10)}),b("spike_operator_join",{A:textShadow("apple"),B:textShadow("banana")}),b("spike_operator_letter",{INDEX:numShadow(1),TEXT:textShadow("apple")}),b("spike_operator_length",{TEXT:textShadow("apple")}),b("spike_operator_contains",{TEXT:textShadow("apple"),PART:textShadow("a")}),b("spike_operator_mod",{A:numShadow(0),B:numShadow(0)}),b("spike_operator_round",{VALUE:numShadow(0)}),b("spike_operator_mathop",{VALUE:numShadow(0)})]),
  ] };
}
